# Generated by Django 5.1.3 on 2024-12-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
